#!/usr/bin/env sh
#copyright john morris beck 2026 gpl2
elfc_source '#!/usr/bin/sh
#copyright john morris beck 2026 gpl2
fastdir="/tmp/.fastlang";
elfc(){ awk  '\''BEGIN{
b=",PROT_READ|PROT_WRITE,MAP_SHARED,(int)(intptr_t)";}
function i(i){return substr($0,1+i,1)}function r(i){return "r["i"]"}
function p(i){return "p["i"]"}
$1=="c"{for(i(i=2;i<=NF;i+=4){printf "%s" $i}print}
$1!="c"{if(substr($1,1,1)!="#"){for(c=1;c<=length($0);c++){
d["+"]=r(i(3))"="r(i(3))r(i(2))r(i(4));
d["f"]=r(i(2))"=open("r(i(3))",O_RDWR)";
d["t"]="ftruncate("r(i(2))","r(i(3))")";
d["a"]=p(i(2))"=(int*)mmap(0,r(i(3))"b r(i(4))",0)";
d["d"]="munmap("p(i(3))","r(i(4))")";
d["p"]=p(i(2))"="p(i(3));
d["c"]="memcpy("p(i(2))","p(i(3))","r(i(4))")";
d["b"]=r(i(2))"="i(3);
d["i"]=r(i(2))"=getchar()";
d["o"]="putchar("p(r(i(2)))"["r(i(3))"])";
d["r"]=r(i(2))"=*("p(r(i(3)))")";
d["w"]="*"p(r(i(3)))"="r(i(2));
d["\""]="for(int i=0;i<"r(i(2))";s[i]=*(*"p(r(i(4)))"+i++))";
d["l"]="while("r(i(2))"){";
d["j"]="switch("r(i(2))"){";
d["}"]="}";
d[";"]="break";
d["$"]="case "i(3)":"
d["x"]="exit(0)"
print d[t]";"}}}}}'\''>"/tmp/.fastlang/$1.c";};
elfc_compile(){
filcc "/tmp/.fastlang/$1.c" -o "/tmp/.fastlang/$1.exe";
chmod +x "/tmp/.fastlang/$1.exe";};
elfc_execute(){ {cat "/tmp/fastlang/shinit.sh;
"/tmp/.fastlang/$1.exe";}|sh;};
elfc_collect(){ rm "/tmp/.fastlang/$1";};';
if [ ! - d /tmp/.fastlang ];then
    mkdir "/tmp/.fastlang";
    printf "%s" "$elfc_source">/tmp/.fastlang/config.sh;fi;
eval "$elfc_source";
