#!/usr/bin/env sh
#copyright john morrris beck 2026 gpl2
fastjit(){ cat>"$1/$2.c";filcc "$1/$2.c" -o "$1/$2.exe";
           rm "$1/$2.c";chmod +x "$1/$2.exe";};
elfc(){ awk  'function i(i){return substr($0,1+i,1)}
function r(i){return "r["i"]"}function p(i){return "p["i"]"}
$2=="c"{for(i(i=2;i<=NF;i+=4){printf "%s" $i}print}
$2!="c"{if(substr($2,1,1)!="#"){for(c=1;c<=length($0);c++){
b=",PROT_READ|PROT_WRITE,MAP_SHARED,(int)(intptr_t)";}
d["+"]=r(i(3))"="r(i(3))r(i(2))r(i(4));
d["f"]=r(i(2))"=open("r(i(3))",O_RDWR)";
d["t"]="ftruncate("r(i(2))","r(i(3))")";
d["a"]=p(i(2))"=(int*)mmap(0,r(i(3))"b r(i(4))",0)";
d["d"]="munmap("p(i(3))","r(i(4))")";
d["p"]=p(i(2))"="p(i(3));
d["c"]="memcpy("p(i(2))","p(i(3))","r(i(4))")";
d["b"]=r(i(2))"="i(3);
d["i"]=r(i(2))"=getchar()";
d["o"]="putchar("p(r(i(2)))"["r(i(3))"])";
d["r"]=r(i(2))"=*("p(r(i(3)))")";
d["w"]="*"p(r(i(3)))"="r(i(2));
d["\""]="free(s);s=malloc(r(i(2)));for(int i=0;i<"r(i(2))";s[i]=*(char*)(*"p(r(i(4)))"+i++))";
d["l"]="while("r(i(2))"){";
d["j"]="switch("r(i(2))"){";
d["}"]="}";
d[";"]="break";
d["T"]="case "i(3)":"
d["x"]="exit(0)"
d["$"]=system(s);
print d[t]";"}}}}';};
